INSERT INTO Libro (id, nome, autore, descrizione, categoria, publisher, prezzo, mesepub, annopub)
VALUES (1, 'Il Grande Gatsby', 'F. Scott Fitzgerald', 'Un classico della letteratura americana.', 'Romanzo', 'Scribner',
        12.99, 'Aprile', 1925),
       (2, '1984', 'George Orwell', 'Un romanzo distopico su un futuro totalitario.', 'Fantascienza',
        'Secker & Warburg', 10.50, 'Giugno', 1949),
       (3, 'Orgoglio e pregiudizio', 'Jane Austen', 'Una storia d’amore e di crescita personale.', 'Romanzo',
        'T. Egerton', 9.99, 'Gennaio', 1813),
       (4, 'Il Signore degli Anelli', 'J.R.R. Tolkien',
        'Un epico viaggio in una terra fantastica chiamata Terra di Mezzo.', 'Fantasy', 'Allen & Unwin', 15.75,
        'Luglio', 1954),
       (5, 'Cime tempestose', 'Emily Brontë', 'Una storia di amore e vendetta nelle brughiere inglesi.', 'Romanzo',
        'Thomas Cautley Newby', 8.25, 'Dicembre', 1847),
       (6, 'Il vecchio e il mare', 'Ernest Hemingway', 'La lotta di un vecchio pescatore contro un grande marlin.',
        'Romanzo', 'Charles Scribner''s Sons', 11.00, 'Settembre', 1952),
       (7, 'Guerra e Pace', 'Lev Tolstoj',
        'Un romanzo storico che descrive la società russa durante le guerre napoleoniche.', 'Storico',
        'The Russian Messenger', 14.99, 'Gennaio', 1869),
       (8, 'Il codice Da Vinci', 'Dan Brown', 'Un thriller che combina religione, arte e teoria del complotto.',
        'Thriller', 'Doubleday', 13.45, 'Marzo', 2003),
       (9, 'Lo Hobbit', 'J.R.R. Tolkien', 'Le avventure di Bilbo Baggins nella Terra di Mezzo.', 'Fantasy',
        'George Allen & Unwin', 10.99, 'Settembre', 1937),
       (10, 'Il nome della rosa', 'Umberto Eco', 'Un mistero medievale ambientato in un monastero italiano.', 'Romanzo',
        'Bompiani', 16.00, 'Aprile', 1980),
       (11, 'La Divina Commedia', 'Dante Alighieri', 'Un viaggio attraverso l''inferno, il purgatorio e il paradiso.',
        'Poesia', 'Società Dantesca Italiana', 18.50, 'Maggio', 1320),
       (12, 'I promessi sposi', 'Alessandro Manzoni',
        'Una storia di amore e redenzione nella Lombardia del XVII secolo.', 'Romanzo', 'Fratelli Treves Editori',
        14.25, 'Luglio', 1840),
       (13, 'Moby Dick', 'Herman Melville', 'La caccia ossessiva del capitano Ahab alla balena bianca Moby Dick.',
        'Avventura', 'Richard Bentley', 17.99, 'Ottobre', 1851),
       (14, 'Don Chisciotte', 'Miguel de Cervantes',
        'Le avventure di un cavaliere errante e il suo fedele scudiero Sancho Panza.', 'Romanzo', 'Francisco de Robles',
        15.00, 'Gennaio', 1605),
       (15, 'I miserabili', 'Victor Hugo', 'Una storia di redenzione e rivoluzione nella Francia del XIX secolo.',
        'Storico', 'A. Lacroix, Verboeckhoven & Cie', 19.99, 'Aprile', 1862),
       (16, 'Anna Karenina', 'Lev Tolstoj', 'Una storia di amore e tragedia nella società russa.', 'Romanzo',
        'The Russian Messenger', 16.75, 'Gennaio', 1877),
       (17, 'Crime e castigo', 'Fëdor Dostoevskij',
        'Un romanzo psicologico su un giovane studente che commette un omicidio.', 'Romanzo', 'The Russian Messenger',
        14.50, 'Gennaio', 1866),
       (18, 'Il conte di Montecristo', 'Alexandre Dumas', 'Una storia di vendetta e giustizia ambientata in Francia.',
        'Avventura', 'Pétion', 15.25, 'Agosto', 1844),
       (19, 'I tre moschettieri', 'Alexandre Dumas',
        'Una storia di avventura e amicizia nella Francia del XVII secolo.', 'Avventura', 'Baudry', 13.75, 'Marzo',
        1844),
       (20, 'Il ritratto di Dorian Gray', 'Oscar Wilde',
        'Un romanzo su un uomo che vende la sua anima per la giovinezza eterna.', 'Romanzo', 'Ward, Lock and Company',
        12.00, 'Luglio', 1890),
       (21, 'Harry Potter e la Pietra Filosofale', 'J.K. Rowling',
        'La storia di un giovane mago che scopre di essere un mago e va a studiare a Hogwarts.', 'Fantasy',
        'Bloomsbury', 14.99, 'Giugno', 1997),
       (22, 'Il Codice Da Vinci', 'Dan Brown', 'Un thriller che combina religione, arte e teoria del complotto.',
        'Thriller', 'Mondadori', 13.45, 'Marzo', 2003),
       (23, 'Angeli e Demoni', 'Dan Brown',
        'Un thriller che segue il professor Robert Langdon in una caccia contro il tempo per salvare il Vaticano.',
        'Thriller', 'Mondadori', 13.45, 'Maggio', 2000),
       (24, 'Il Simbolo Perduto', 'Dan Brown',
        'Un thriller che vede Robert Langdon alla ricerca di un antico mistero massonico.', 'Thriller', 'Mondadori',
        13.45, 'Settembre', 2009),
       (25, 'Inferno', 'Dan Brown',
        'Un thriller in cui Robert Langdon deve risolvere un enigma legato alla Divina Commedia di Dante.', 'Thriller',
        'Mondadori', 13.45, 'Maggio', 2013),
       (26, 'Origine', 'Dan Brown',
        'Un thriller che vede Robert Langdon in Spagna alla ricerca di una scoperta che cambierà la storia dell''umanità.',
        'Thriller', 'Mondadori', 13.45, 'Ottobre', 2017),
       (27, 'La ragazza del treno', 'Paula Hawkins',
        'Un thriller psicologico che segue una donna che diventa coinvolta in un mistero dopo aver visto qualcosa da un treno.',
        'Thriller', 'Penguin', 11.99, 'Gennaio', 2015),
       (28, 'Gone Girl', 'Gillian Flynn',
        'Un thriller psicologico che esplora la scomparsa di una donna e i sospetti che cadono sul marito.', 'Thriller',
        'Crown', 12.99, 'Maggio', 2012),
       (29, 'Il cacciatore di aquiloni', 'Khaled Hosseini',
        'Una storia di amicizia e redenzione ambientata in Afghanistan.', 'Romanzo', 'Riverhead Books', 11.50, 'Maggio',
        2003),
       (30, 'Mille splendidi soli', 'Khaled Hosseini', 'Una storia di due donne afghane e delle loro lotte e trionfi.',
        'Romanzo', 'Riverhead Books', 11.50, 'Maggio', 2007),
       (31, 'E poi l''abbiamo uccisa', 'Khaled Hosseini',
        'Una storia di famiglia, amore e sacrificio che si svolge tra Afghanistan e Grecia.', 'Romanzo',
        'Riverhead Books', 11.50, 'Maggio', 2013),
       (32, 'Il signore delle mosche', 'William Golding',
        'Un romanzo allegorico su un gruppo di ragazzi bloccati su un''isola deserta.', 'Romanzo', 'Faber and Faber',
        10.99, 'Settembre', 1954),
       (33, 'Il giovane Holden', 'J.D. Salinger',
        'La storia di Holden Caulfield, un adolescente che racconta le sue esperienze a New York City.', 'Romanzo',
        'Little, Brown and Company', 10.50, 'Luglio', 1951),
       (34, 'Il buio oltre la siepe', 'Harper Lee',
        'La storia di un avvocato che difende un uomo di colore accusato ingiustamente di stupro.', 'Romanzo',
        'J. B. Lippincott & Co.', 11.25, 'Luglio', 1960),
       (35, 'Fight Club', 'Chuck Palahniuk',
        'Un romanzo che segue un uomo che crea un club di combattimento clandestino.', 'Romanzo',
        'W. W. Norton & Company', 12.75, 'Agosto', 1996),
       (36, 'Shantaram', 'Gregory David Roberts',
        'Una storia semi-autobiografica di un uomo che fugge da una prigione australiana e si rifugia a Bombay.',
        'Romanzo', 'St. Martin''s Press', 14.99, 'Ottobre', 1993),
       (37, 'La ragazza con l''orecchino di perla', 'Tracy Chevalier',
        'Un romanzo storico ispirato al dipinto omonimo di Vermeer.', 'Romanzo', 'Dutton', 11.99, 'Settembre', 1999),
       (38, 'Il paziente inglese', 'Michael Ondaatje',
        'Una storia d''amore e perdita ambientata durante la Seconda Guerra Mondiale.', 'Romanzo', 'Bloomsbury', 12.50,
        'Settembre', 1992),
       (39, 'Il mondo nuovo', 'Aldous Huxley',
        'Un romanzo distopico che immagina un futuro in cui la società è controllata attraverso la tecnologia e il condizionamento.',
        'Fantascienza', 'Chatto & Windus', 11.75, 'Gennaio', 1932),
       (40, 'Fahrenheit 451', 'Ray Bradbury',
        'Un romanzo distopico che segue un futuro in cui i libri sono vietati e i vigili del fuoco bruciano le case che li contengono.',
        'Fantascienza', 'Ballantine Books', 10.99, 'Ottobre', 1953),
       (41, 'Le confessioni d''un italiano', 'Ippolito Nievo',
        'Un romanzo storico che racconta la vita di un nobile italiano durante il Risorgimento.', 'Storico', 'Garzanti',
        14.99, 'Gennaio', 1867),
       (42, 'Il castello di Fratta', 'Ippolito Nievo',
        'Una storia di amore e mistero ambientata in un castello del Friuli.', 'Romanzo', 'Mondadori', 13.50, 'Marzo',
        1887),
       (43, 'La vita di un italiano', 'Ippolito Nievo',
        'Una raccolta di scritti autobiografici e riflessioni sulla vita e la società italiana.', 'Autobiografia',
        'Einaudi', 12.99, 'Settembre', 1858),
       (44, 'Una senz''arte', 'Italo Svevo',
        'Una commedia che esplora le dinamiche sociali e familiari nella Trieste del primo Novecento.', 'Commedia',
        'Einaudi', 11.75, 'Gennaio', 1892),
       (45, 'La coscienza di Zeno', 'Italo Svevo',
        'Un romanzo psicologico che esplora la vita e le nevrosi del protagonista Zeno Cosini.', 'Romanzo', 'Einaudi',
        14.50, 'Dicembre', 1923),
       (46, 'Corto viaggio sentimentale', 'Italo Svevo',
        'Una raccolta di racconti brevi che esplorano le relazioni umane e le emozioni.', 'Racconti', 'Einaudi', 12.25,
        'Luglio', 1947),
       (47, 'La novella dello scaccino', 'Italo Svevo',
        'Una novella che racconta la storia di un uomo ossessionato dal gioco degli scacchi.', 'Novella', 'Einaudi',
        10.99, 'Marzo', 1962),
       (48, 'Una burla riuscita', 'Italo Svevo', 'Una commedia che esplora le dinamiche sociali e le relazioni umane.',
        'Commedia', 'Einaudi', 11.50, 'Settembre', 1928),
       (49, 'La tribù dei sognatori solitari', 'Italo Svevo',
        'Una raccolta di scritti che esplorano i sogni e le aspirazioni dell''autore.', 'Racconti', 'Einaudi', 13.00,
        'Gennaio', 1972),
       (50, 'Finnish Lessons: What Can the World Learn from Educational Change in Finland?', 'Pasi Sahlberg',
        'Un''analisi del sistema educativo finlandese e delle lezioni che può offrire al mondo.', 'Saggio',
        'Teachers College Press', 19.99, 'Maggio', 2011),
       (51, 'Finnish Lessons 2.0: What Can the World Learn from Educational Change in Finland?', 'Pasi Sahlberg',
        'Un aggiornamento dell''analisi del sistema educativo finlandese e delle sue riforme.', 'Saggio',
        'Teachers College Press', 21.99, 'Settembre', 2014),
       (52, 'Hard Questions on Global Educational Change: Policies, Practices, and the Future of Education',
        'Pasi Sahlberg',
        'Una raccolta di saggi che esplorano le sfide e le opportunità del cambiamento educativo globale.', 'Saggio',
        'Teachers College Press', 22.99, 'Gennaio', 2021),
       (53, 'Lettere di un gatto viaggiatore', 'Refosco',
        'Una raccolta di lettere che raccontano le avventure di un gatto che viaggia per il mondo.', 'Romanzo',
        'Mondadori', 12.50, 'Luglio', 2018),
       (54, 'Il gatto che sapeva troppo', 'Lilian Jackson Braun',
        'Un mistero che vede un gatto aiutare il suo umano a risolvere un caso di omicidio.', 'Giallo', 'Signet', 11.99,
        'Marzo', 1996),
       (55, 'Il gatto che veniva dal freddo', 'Refosco',
        'La storia di un gatto che viaggia dall''Artico alla ricerca di una nuova casa.', 'Romanzo', 'Mondadori', 13.25,
        'Settembre', 2016),
       (56, 'Il gatto con gli stivali', 'Charles Perrault',
        'La fiaba classica di un gatto che aiuta il suo padrone a diventare ricco e famoso.', 'Fiaba', 'Einaudi', 10.50,
        'Gennaio', 1697),
       (57, 'Il gatto che amava i libri', 'Sosuke Natsukawa',
        'La storia di un gatto che aiuta a gestire una libreria e a salvare i libri da un destino oscuro.', 'Romanzo',
        'Feltrinelli', 14.99, 'Marzo', 2017),
       (58, 'Il gatto che trovava le stelle', 'Refosco',
        'La storia di un gatto che aiuta le persone a trovare la felicità e la speranza.', 'Romanzo', 'Mondadori',
        12.75, 'Luglio', 2019),
       (59, 'Il gatto che voleva tornare a casa', 'Refosco',
        'La storia di un gatto che intraprende un lungo viaggio per tornare a casa.', 'Romanzo', 'Mondadori', 11.99,
        'Gennaio', 2017),
       (60, 'Il gatto che sapeva leggere', 'Refosco',
        'La storia di un gatto che impara a leggere e cambia la vita delle persone intorno a lui.', 'Romanzo',
        'Mondadori', 13.50, 'Marzo', 2020);
